[package]
name = "siming-desktop"
description = "Tauri desktop shell for Siming."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "siming_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde.workspace = true
serde_json.workspace = true
siming-core.workspace = true
siming-storage.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
